### PR TITLE
Remove the ability to set custom client id in CassandraLockConfig. 

### LINKED ISSUE #43: CassandraLockConfig.withClientId() method is prone to accidental misuse
In order for the locking mechanism to work, each application instance has to use a unique client ID.

The [`CassandraLockConfig.withClientId()` method](https://github.com/sky-uk/cqlmigrate/blob/master/src/main/java/uk/sky/cqlmigrate/CassandraLockConfig.java#L31-L35) is potentially misleading - if a client application uses a static value for this, instead of a UUID, then multiple instances can share the same lock and schema chaos may result.

@adamdougal and I believe this method should be either:
-  removed entirely, or
-  at least renamed to make it clear that the value provided should be a unique ID.

### PR DESCRIPTION
**Pull request by razvanth**
Use default generated random client id. Fixes #43.

### CODE REVIEW

**Comment by adamdougal** [comment]
Need to update the README.md to show that we no longer take the clientId as a parameter.
Other then that, lgtm.

**Comment by razvanth** [comment]
Thanks @adamdougal. That's been updated now.

**Comment by oliverlockwood** [comment]
:+1: Merging this; I'll get a release out shortly.

**Comment by oliverlockwood** [comment]
@razvanth this has now been released as version [0.9.6](https://github.com/sky-uk/cqlmigrate/releases/tag/0.9.6).

**Pull request merged**
