### PR TITLE
Update cassandra driver 4xx

### PR DESCRIPTION
**Pull request by sethishi**
- updated code to use latest cassandra driver version 4.x
- removed _scassandra_ and replaced tests with **simulacron** (maintained by datastax)
- updated the latest version of cassandra-unit compatible with 4.x
- the latest driver doesn't allow changing column types; this failed some existing tests that need to be updated to be compatible with driver 4.x

### CODE REVIEW

**Comment by fincefid** [comment]
@sethishi Is there any update on that PR? 
Anything we can help to get this going?

**Comment by sethishi** [comment]
@fincefid, sorry haven't been able to spend time on cqlmigrate. There were a few tests that needed review at the time this was done. Also, I tried merging in the changes and that required quite a bit of time. Would be nice to get some help on this. Can contact over slack and see what we can do to progress on this.

**Comment by aandres-medallia** [comment]
is there any update on this PR? is there any way I can help?

**Comment by sethishi** [comment]
For integration tests we have had to use simulacron library but unfortunately simulacron is unable to add metadata information to the simulated cluster. Cqlmigrate depends on metadata from the cluster. Have raised the issue with datastax to see if they can provide any help with this. https://github.com/datastax/simulacron/issues/104

**Comment by aandres-medallia** [comment]
@sethishi I'm not sure if you've seen datastax response. How can I help you with this PR?

**Comment by alexguzun** [comment]
Hi! Any updates on this PR? We would really like to use `cqlmigrate` in our new component, but we have to use the 4.xx version of the Cassandra driver.

**Comment by sethishi** [comment]
Sorry guys, the work is in progress and due to other high priority work we haven't been able to get this one through.

**Comment by bluedigits** [comment]
Any updates on this one? It would be really great if we could use `cqlmigrate` but we need to stick to driver version 4.x

**Comment by StephenRileySky** [comment]
@sethishi  can we move this PR on please?

**Comment by sethishi** [comment]
We have made progress on the update. Possibly will be a new PR with the latest changes. This PR is a bit outdated.

**Comment by adamdougal** [comment]
@sethishi Is this still a work in progress? It looks like your branch has gotten quite out of date with master. If so, is there any eta on the work being completed? Thanks

**Comment by sethishi** [comment]
Work has been merged as part of another PR, closing the PR

**Pull request closed without merging**
